name: "Create Issue Comment via API"

on:
  repository_dispatch:
    types: [webhook]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Make a comment on the issue
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/salamin-tr-galt/hello-world/issues/${{ github.event.inputs.issue_id }}/comments \
          -d '{"body": "${{ github.event.inputs.comment_body }}"}'
