name: "Create Issue Comment via API"

on:
  workflow_dispatch:
    inputs:
      issue_id:
        description: "ID of the GitHub issue to comment on"
        required: true
      comment_body:
        description: "The content of the comment"
        required: true

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Make a comment on the issue
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/salamin-tr-galt/hello-world/issues/${{ github.event.inputs.issue_id }}/comments \
          -d '{"body": "${{ github.event.inputs.comment_body }}"}'
